package main

import (
    "encoding/json"
    "fmt"
    "io/ioutil"
    "net/http"
    "time"
)

type CryptoPrice struct {
    USD             float64 `json:"usd"`
    USD_24H_CHANGE float64 `json:"usd_24h_change"`
}

type CryptoData map[string]CryptoPrice

func main() {
    // 获取加密货币价格和24小时变化
    url := "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin,ethereum&vs_currencies=usd&include_24hr_change=true"
    resp, err := http.Get(url)
    if err != nil {
        fmt.Println("Error fetching data:", err)
        return
    }
    defer resp.Body.Close()

    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        fmt.Println("Error reading response:", err)
        return
    }

    var data CryptoData
    if err := json.Unmarshal(body, &data); err != nil {
        fmt.Println("Error decoding JSON:", err)
        return
    }

    // 生成动态 README 内容，使用 Emoji 和格式优化
    content := fmt.Sprintf(`# Crypto Trader Profile 🚀

Hey there! I'm a passionate **Crypto Trader** riding the blockchain waves 🌊!

## 🌟 Live Market Snapshot
*Last Updated: %s* ⏰

| Coin       | Price (USD)    | Trend  |
|------------|----------------|--------|
| **Bitcoin (BTC)** ₿ | $%.2f (%.2f%%) | %s |
| **Ethereum (ETH)** Ξ | $%.2f (%.2f%%) | %s |

## 🛠️ Tech Stack & Skills
- **Languages**: Go, Python, JavaScript 💻
- **Blockchain**: Smart Contracts, DeFi Protocols 🔗
- **Trading**: Technical Analysis, Risk Management 📊
- **Tools**: Trading Bots, Market Analysis Tools 🤖

## 💡 Trader's Wisdom
*"Buy the dip 📉, sell the rip 📈, and HODL like a champ! 💎🙌"*

## 📬 Stay Connected
- Follow my trades on [Twitter](https://twitter.com/A1rChina) 🐦

<!--- Auto-generated by GitHub Actions 🤖 --->
`,
    time.Now().Format(time.RFC1123),
    data["bitcoin"].USD, data["bitcoin"].USD_24H_CHANGE, trendEmoji(data["bitcoin"].USD, data["bitcoin"].USD_24H_CHANGE),
    data["ethereum"].USD, data["ethereum"].USD_24H_CHANGE, trendEmoji(data["ethereum"].USD, data["ethereum"].USD_24H_CHANGE),
)

    // 写入 README.md
    if err := ioutil.WriteFile("README.md", []byte(content), 0644); err != nil {
        fmt.Println("Error writing to README:", err)
    }
}

// 根据24小时价格变化显示趋势 Emoji
func trendEmoji(_ float64, change float64) string {
    switch {
    case change > 10.0:  // 大幅上涨（超过10%）
        return "🚀"
    case change > 3.0:   // 中等上涨（3-10%）
        return "📈"
    case change >= -3.0: // 稳定区间（-3% 到 3%）
        return "➡️"
    case change >= -10.0: // 中等下跌（-3% 到 -10%）
        return "📉"
    default:            // 大幅下跌（超过-10%）
        return "💎"
    }
}